# Generated by Django 4.1.4 on 2022-12-11 17:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='fee_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
